#application.yml
spring:
  application:
    name: zyy
    #模板配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  # 热部署, 修改类和资源时不重启服务
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java  #重启目录
      exclude: static/**  #设置classpath下 static 目录内容修改后不重启。一般设置为静态资源目录
    freemarker:
      cache: false  #页面不加载缓存，修改即时生效
  # 缩进两格，配置jdbc数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.186.4:3306/zyydbtest?serverTimezone=UTC
    username: root
    password: Eleven_rocks11
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: TutorialsHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
# 分页
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  supportMethodsArguments: true
  returnPageInfo: true
  params: count=countSql


# 开放所有的 Web endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 输出 mybatis SQL日志
logging:
  level:
    root: INFO
  pattern:
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
  #config: classpath:logback-dev.xml
  #file:
    #日志文件路径D:/My_IDEA/lanqiaoprojs/zyysys/zyysys/zyysyslog
    #path: D:/My_IDEA/lanqiaoprojs/zyysys/zyysys/zyysyslog

#可以在idea的启动配置中覆盖此属性来启动多个server

#server:
#配置内置tomcat端口和上下文根
server:
  port: 9001
  servlet:
    context-path: /zyysys